### ISSUE TITLE
Crash when running compiled jar

### ISSUE THREAD

**Issue by teodorlu** [casidiablo/slack-rtm#24]
Hello!

Thanks for making this. I'm having issues running a compiled .jar. The error may well be on my side, but if you have the time I'd like your insight!

## Problem description

When I run my bot with `boot run`, the bot works as expected.

When I first compile (`boot build`), then run the jar (`java -jar target/preik-0.1.0-SNAPSHOT-standalone.jar`), I get a security error from Java: `Exception in thread "main" java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`.

The entry point in my code is `(slack/connect (env :slack-api-key))`.

## System

- Ubuntu 17.04
- Boot 2.7.2
- Clojure 1.9.0 (also tested 1.8.0)
- Oracle Java 9 (also tested OpenJDK 8 and OpenJDK 9)

## Stack trace and source code

Running my application gives me this:

```
$ SLACK_API_KEY=xoxb-1111restofthekey java -jar target/preik-0.1.0-SNAPSHOT-standalone.jar
Exception in thread "main" java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:86)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:330)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:180)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:192)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at java.base/sun.security.ssl.ClientHandshaker.checkServerCerts(ClientHandshaker.java:1947)
	at java.base/sun.security.ssl.ClientHandshaker.certificateStatus(ClientHandshaker.java:1798)
	at java.base/sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:276)
	at java.base/sun.security.ssl.Handshaker.processLoop(Handshaker.java:1092)
	at java.base/sun.security.ssl.Handshaker.processRecord(Handshaker.java:1026)
	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(SSLSocketImpl.java:1137)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1402)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1429)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:543)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at clj_http.core$request.invokeStatic(core.clj:298)
	at clj_http.core$request.invoke(core.clj:208)
	at clojure.lang.Var.invoke(Var.java:381)
	at clj_http.client$wrap_request_timing$fn__2411.invoke(client.clj:796)
	at clj_http.headers$wrap_header_map$fn__1106.invoke(headers.clj:143)
	at clj_http.client$wrap_query_params$fn__2318.invoke(client.clj:624)
	at clj_http.client$wrap_basic_auth$fn__2325.invoke(client.clj:640)
	at clj_http.client$wrap_oauth$fn__2329.invoke(client.clj:650)
	at clj_http.client$wrap_user_info$fn__2334.invoke(client.clj:663)
	at clj_http.client$wrap_url$fn__2397.invoke(client.clj:762)
	at clj_http.client$wrap_redirects$fn__2140.invoke(client.clj:237)
	at clj_http.client$wrap_decompression$fn__2159.invoke(client.clj:309)
	at clj_http.client$wrap_input_coercion$fn__2253.invoke(client.clj:488)
	at clj_http.client$wrap_additional_header_parsing$fn__2274.invoke(client.clj:522)
	at clj_http.client$wrap_output_coercion$fn__2244.invoke(client.clj:438)
	at clj_http.client$wrap_exceptions$fn__2126.invoke(client.clj:189)
	at clj_http.client$wrap_accept$fn__2288.invoke(client.clj:565)
	at clj_http.client$wrap_accept_encoding$fn__2294.invoke(client.clj:579)
	at clj_http.client$wrap_content_type$fn__2283.invoke(client.clj:555)
	at clj_http.client$wrap_form_params$fn__2371.invoke(client.clj:726)
	at clj_http.client$wrap_nested_params$fn__2392.invoke(client.clj:751)
	at clj_http.client$wrap_method$fn__2341.invoke(client.clj:670)
	at clj_http.cookies$wrap_cookies$fn__334.invoke(cookies.clj:124)
	at clj_http.links$wrap_links$fn__1316.invoke(links.clj:51)
	at clj_http.client$wrap_unknown_host$fn__2401.invoke(client.clj:771)
	at clj_http.client$get.invokeStatic(client.clj:874)
	at clj_http.client$get.doInvoke(client.clj:870)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clj_slack.core$send_request.invokeStatic(core.clj:36)
	at clj_slack.core$send_request.invoke(core.clj:32)
	at clj_slack.core$slack_request.invokeStatic(core.clj:82)
	at clj_slack.core$slack_request.invoke(core.clj:76)
	at clj_slack.core$slack_request.invokeStatic(core.clj:78)
	at clj_slack.core$slack_request.invoke(core.clj:76)
	at clj_slack.rtm$connect.invokeStatic(rtm.clj:13)
	at clj_slack.rtm$connect.invoke(rtm.clj:9)
	at slack_rtm.core$internal_connect.invokeStatic(core.clj:151)
	at slack_rtm.core$internal_connect.doInvoke(core.clj:107)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$apply.invoke(core.clj:652)
	at slack_rtm.core$connect.invokeStatic(core.clj:165)
	at slack_rtm.core$connect.doInvoke(core.clj:164)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at preik.core$_main.invokeStatic(core.clj:65)
	at preik.core$_main.doInvoke(core.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at preik.core.main(Unknown Source)
```

More details are available at the [full project](https://github.com/teodorlu/preik).

**Comment by teodorlu** [comment]
Hello!

The issue was not with slack-rtm, but with the Java installation. Specifically, `/etc/ssl/certs/java/cacerts` was broken.

Fix:

1. Download and extract JDK from Oracle. I ran `tar -xvf jdk-9.0.4_linux-x64_bin.tar.gz`, which gave me a `jdk-9.0.4` folder.
2. Replace the `cacerts` file: `sudo cp jdk-9.0.4/lib/security/cacerts /etc/ssl/certs/java/cacerts`.

Closing this.
