### ISSUE TITLE
Errors with channel put limits

### ISSUE THREAD

**Issue by RiadVargas** [casidiablo/slack-rtm#25]
I'm experiencing some problems when listening to `message` event. Here's an excerpt of the problem:

```
Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
(< (.size puts) impl/MAX-QUEUE-SIZE)
        at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:152)
        at clojure.core.async.impl.ioc_macros$put_BANG_.invokeStatic(ioc_macros.clj:992)
        at clojure.core.async.impl.ioc_macros$put_BANG_.invoke(ioc_macros.clj:991)
        at slack_rtm.core$ws_connect$fn__12465$fn__12481$state_machine__9446__auto____12488$fn__12490.invoke(core.clj:38)
        at slack_rtm.core$ws_connect$fn__12465$fn__12481$state_machine__9446__auto____12488.invoke(core.clj:38)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at slack_rtm.core$ws_connect$fn__12465$fn__12481.invoke(core.clj:38)
```
Apparently this error doesn't affect new messages listening so I don't get what's the real impact of it. Seems to be related with `clojure.core.async` channels.

**Comment by casidiablo** [comment]
Is this easy to reproduce? Would it be possible for you to share an excerpt of the code you are working with?

**Comment by RiadVargas** [comment]
@casidiablo To reproduce I've just let the application up for some minutes and that error started to show up.
Here's the code:
```
(require '[slack-rtm.core :as rtm])
(require '[clj-slack.groups :as groups])

(def rtm-conn (rtm/rtm-connect *TOKEN*))

(def events-publication (:events-publication rtm-conn))

(rtm/sub-to-event events-publication :pong)
(def dispatcher (:dispatcher rtm-conn))
(rtm/send-event dispatcher {:type \"ping\"}) ;; To avoid constant disconnects                                                                                                                  

(defn message-receiver [e]
  (when (and (= channel-name (get e :channel))
             (not (get e :subtype false))
             (not (get e :edited false))
             (not (get e :thread_ts false)))
    (doto queue (.put (new sisc.data.ImmutableString (get e :text))))))
(rtm/sub-to-event events-publication :message message-receiver)
```

**Comment by RiadVargas** [comment]
Just to update: this problem was being caused because I was creating a listener for each channel (I need to separate each message from a channel and put in their respective queue), so I solved this issue by changing a little bit my logic and putting a single listener accessing all the queues and channels.
Closing it.
